<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />

  <PropertyGroup>
    <Version>7.0.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
    <DefineConstants>$(DefineConstants);DOTNET</DefineConstants>
    <AssemblyName>dotnet-bundle</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>BundlerMinifier.Core.Tool</PackageId>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>bundle</ToolCommandName>
    <RootNamespace>BundlerMinifier</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>


  <ItemGroup>
    <!--
      This file instructs dotnet.exe to use whichever version of .NET Core is installed,
      which may not be the version this tool is compiled against.
    -->
    <Content Include="prefercliruntime" Pack="true" PackagePath="\prefercliruntime" />
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUglify" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
