name: update if nuglify released a new version

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2
        with:
          ref: 'raif'
          token: ${{ secrets.PAT }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Configure git
        run: |
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
          echo "#!/bin/sh" > ~/.gpg-pinentry-loopback
          echo "gpg --pinentry-mode loopback $@" >> ~/.gpg-pinentry-loopback
          chmod +x ~/.gpg-pinentry-loopback
          GPG_TTY=$(tty) /home/runner/.gpg-pinentry-loopback --status-fd=2 -bsau 5F4D97A509FAFFFA
          git config --global gpg.program "$HOME/.gpg-pinentry-loopback"
          touch test
          git add test
          GIT_TRACE=1 git commit -S -m "Test"
          git reset --hard HEAD~1
      - name: Update NUglify version
        run: |
          NUGLIFY=$(curl -s https://www.nuget.org/packages/NUglify/atom.xml \
          | grep -oPm1 "(?<=<id>https://www.nuget.org/packages/NUglify/)[^<]+" \
          | head -n1); 
          sed -i "s#<PackageReference Include=\"NUglify\" Version=\".*\" />#<PackageReference Include=\"NUglify\" Version=\"$NUGLIFY\" />#" src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          sed -i -r 's#<Version>(.*)\.([[:digit:]]+)</Version>#echo "    <Version>\1\.$((\2+1))</Version>"#e' src/BundlerMinifier.Core/BundlerMinifier.Core.csproj
          git commit -am "New version tracking new NUglify release"
          git push
